name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Lint commit message(s)
        run: |
          yarn add @commitlint/cli
          yarn add @commitlint/config-conventional
          yarn run commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Run tests
        run: go test ./...

  release:
    if: github.event_name == 'push'

    needs:
      - lint
      - test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: goreleaser/goreleaser-action@v3
        with:
          install-only: true

      - name: Release
        run: |
          yarn add semantic-release
          yarn add @semantic-release/exec
          yarn run semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/upload-artifact@v3
        with:
          name: formula
          path: dist/flux-envsubst.rb

  publish:
    if: github.event_name == 'push'

    needs:
      - release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/homebrew-tap
          ssh-key: ${{ secrets.HOMEBREW_TAP_DEPLOY_KEY }}

      - uses: actions/download-artifact@v3
        with:
          name: formula
          path: Formula/flux-envsubst.rb

      - name: Publish
        run: |
          git add Formula
          git commit -m "Update ${{ github.repository }}"
          git push
